In [8]:
import pandas as pd

df = pd.read_csv("raw\\balanced-reviews.txt", sep="\t", encoding="utf-16", engine='python', on_bad_lines='skip')

df = df.fillna("-")
df = df.sample(frac=1).reset_index(drop=True)

In [9]:
df

,no,Hotel name,rating,user type,room type,nights,review
0,190897,حياة ريجنسى مكة,4,زوج,غرفة بحجم كينغ أو توأمية مع منظر,أقمت 3 ليالي,“فندق جميل يحتاج بعض التعديلات”. قرب الموقع من...
1,357437,فندق سوفيتل الخبرالكورنيش,4,زوج,غرفة سوبيريور بسرير واحد بحجم كوين مطلة على ال...,أقمت ليلة واحدة,“مريحه نوعا ما”. اعجبني حجم الغرفه والنظافه. ع...
2,344618,ساندراس ان,5,مسافر منفرد,غرفة مفردة,أقمت 3 ليالي,استثنائي. الاستاذ سعيد المصري .. صراحة من افضل...
3,275105,نوفوتيل الفجيرة,4,-,غرفة قياسية مع سريرين مفردين,أقمت ليلة واحدة,جيد جداً. هدوء الفندقوالقيمة مناسبه للكل. خدمة...
4,412009,زوار انترناشيونال,2,أسرة,-,أقمت 4 ليالي,مخيب للأمل. التكييف في الغرفةاسرة الغرف. صور غ...
...,...,...,...,...,...,...,...
105693,172224,فندق حياة هوم,1,زوج,-,أقمت ليلتين,“لم تكن الغرفة مطابقة لما تم حجزه ، كما أن صور...
105694,368123,هوتيل سن اند ساندس,1,أسرة,غرفة مزدوجة مع سرير إضافي,أقمت 4 ليالي,ضعيف جداً. للاسف اسوا من السيء. ريحة الغرف وال...
105695,122710,فندق مطار دبي الدولي,2,مسافر منفرد,غرفة ديلوكس في كونكورس A,أقمت ليلة واحدة,“لو لم اكن مضطرا لما اقمت في هذا الفندق”. لا ش...
105696,362656,فندق ساوثرن صن أبوظبي,5,أسرة,غرفة عائلية ديلوكس,أقمت 3 ليالي,“مكان عائلي”. مكان مناسب للعائلات ،، الخدمات م...
105697,324556,رست نايت للأجنحة الفندقية،حي الفلاح,1,أسرة,-,أقمت ليلتين,“غير ممتعه”. لم يعجبني شي ابد. النظافة سيئهالإ...

In [10]:
df.rename(columns={'no': 'order_id','Hotel name':'product','room type':'amount','nights':'date'}, inplace=True)

In [11]:
df = df.drop(columns=["user type"])

In [12]:
dataset = df[:1000]

In [13]:
print(dataset["review"][20])

ضعيف جداً. . استقبال غير لأق

In [14]:
dataset.to_csv("dataset.csv", index=False, encoding="utf-8-sig")

In [15]:
dataset.head()

,order_id,product,rating,amount,date,review
0,190897,حياة ريجنسى مكة,4,غرفة بحجم كينغ أو توأمية مع منظر,أقمت 3 ليالي,“فندق جميل يحتاج بعض التعديلات”. قرب الموقع من...
1,357437,فندق سوفيتل الخبرالكورنيش,4,غرفة سوبيريور بسرير واحد بحجم كوين مطلة على ال...,أقمت ليلة واحدة,“مريحه نوعا ما”. اعجبني حجم الغرفه والنظافه. ع...
2,344618,ساندراس ان,5,غرفة مفردة,أقمت 3 ليالي,استثنائي. الاستاذ سعيد المصري .. صراحة من افضل...
3,275105,نوفوتيل الفجيرة,4,غرفة قياسية مع سريرين مفردين,أقمت ليلة واحدة,جيد جداً. هدوء الفندقوالقيمة مناسبه للكل. خدمة...
4,412009,زوار انترناشيونال,2,-,أقمت 4 ليالي,مخيب للأمل. التكييف في الغرفةاسرة الغرف. صور غ...

In [16]:
test_dataset = dataset.sample(frac=0.075)

In [17]:
test_dataset.head()

,order_id,product,rating,amount,date,review
788,338927,فندق نزل رويال إن,2,غرفة رباعية مع حمام,أقمت 4 ليالي,“ليس بالمستوى المأمول”. . أن معلومات الغرف بال...
666,145846,فندق فلوريدا إنترناشونال,2,غرفة قياسية مزدوجة أو توأم,أقمت ليلة واحدة,مخيب للأمل. الموقع بنص السوق االشعبي وتوجد بلك...
629,85790,فندق سيتي ماكس البرشاء,2,غرفة قياسية,أقمت 3 ليالي,“3”. لا يصلح عوايل. الناس في اليل سكار في ا...
889,364613,ستار مترو ديرة للشقق الفندقية,5,-,أقمت 3 ليالي,ممتاز. المسبح جميل وقرب الفندق من محطة المترو....
86,108333,فندق أبراج الصفوة – دار الغفران,5,غرفة سوبيريور مزدوجة,أقمت ليلتين,“تفرغ للعباده ودع عنك العناء مع فندق دار الغفر...

In [18]:
len(test_dataset)

75

In [19]:
labels = [
    "order_id",
    "product",
    "rating",
    "amount",
    "date",
    "review",
    "intent",
    "urgency",
    "sentiment",
    "dialect",
    "requires_human",
    "routed_team"
  ]

In [20]:
test_dataset_for_fill = pd.DataFrame(columns=labels)

In [21]:
test_dataset_for_fill

Empty DataFrame
Columns: [order_id, product, rating, amount, date, review, intent, urgency, sentiment, dialect, requires_human, routed_team]
Index: []

In [22]:
urgency_map ={
    1: "high",
    2: "high",
    3: "medium",
    4: "low",
    5: "low"
}

sentiment_map ={
    1: "negative",
    2: "negative",
    3: "neutral",
    4: "positive",
    5: "positive"
}

In [23]:
test_dataset_for_fill['order_id'] = test_dataset["order_id"]
test_dataset_for_fill['product'] = test_dataset["product"]
test_dataset_for_fill['rating'] = test_dataset["rating"]
test_dataset_for_fill['amount'] = test_dataset["amount"]
test_dataset_for_fill['date'] = test_dataset["date"]
test_dataset_for_fill['review'] = test_dataset["review"]
test_dataset_for_fill['urgency'] = test_dataset["rating"].map(urgency_map)
test_dataset_for_fill['sentiment'] = test_dataset["rating"].map(sentiment_map)

In [24]:
test_dataset_for_fill

,order_id,product,rating,amount,date,review,intent,urgency,sentiment,dialect,requires_human,routed_team
788,338927,فندق نزل رويال إن,2,غرفة رباعية مع حمام,أقمت 4 ليالي,“ليس بالمستوى المأمول”. . أن معلومات الغرف بال...,NaN,high,negative,NaN,NaN,NaN
666,145846,فندق فلوريدا إنترناشونال,2,غرفة قياسية مزدوجة أو توأم,أقمت ليلة واحدة,مخيب للأمل. الموقع بنص السوق االشعبي وتوجد بلك...,NaN,high,negative,NaN,NaN,NaN
629,85790,فندق سيتي ماكس البرشاء,2,غرفة قياسية,أقمت 3 ليالي,“3”. لا يصلح عوايل. الناس في اليل سكار في ا...,NaN,high,negative,NaN,NaN,NaN
889,364613,ستار مترو ديرة للشقق الفندقية,5,-,أقمت 3 ليالي,ممتاز. المسبح جميل وقرب الفندق من محطة المترو....,NaN,low,positive,NaN,NaN,NaN
86,108333,فندق أبراج الصفوة – دار الغفران,5,غرفة سوبيريور مزدوجة,أقمت ليلتين,“تفرغ للعباده ودع عنك العناء مع فندق دار الغفر...,NaN,low,positive,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
406,94543,فندق كورال الاحساء,2,-,أقمت ليلة واحدة,“فندق زباله وسعره غالي”. لم يعجبني شي للاسف. ا...,NaN,high,negative,NaN,NaN,NaN
188,300774,ربيع العمر للشقق الفندقية,2,-,أقمت ليلة واحدة,مخيب للأمل. . السرير غير مريح أبببببداً,NaN,high,negative,NaN,NaN,NaN
304,107760,فندق دار الايمان جراند,2,-,أقمت 3 ليالي,مخيب للأمل. . المكان بعيد عن الحرم وليس كما ذك...,NaN,high,negative,NaN,NaN,NaN
194,239534,شقق ماريوت الفندقية - مكارم الرياض,5,شقة من غرفة نوم واحدة,أقمت 3 ليالي,“اقامة ممتعة وساقوم بالعودة لشقق ماريوت في اي ...,NaN,low,positive,NaN,NaN,NaN
258,65878,فندق بودل البريدة,2,-,أقمت ليلتين,مخيب للأمل. . عدم التفاهم ولزامك بالخروج ٢.٣٠,NaN,high,negative,NaN,NaN,NaN

In [25]:
test_dataset_for_fill.to_csv("test_dataset_for_fill.csv", index=False, encoding="utf-8-sig")

In [27]:
# after send File to Claude to fill it
test_dataset_filled = pd.read_csv("test_dataset_filled.csv", encoding="utf-8-sig")

In [28]:
test_dataset_filled

,order_id,product,rating,amount,date,review,intent,urgency,sentiment,dialect,requires_human,routed_team
0,58231,فندق أيلا بوادي,5,غرفة كوين كلاسيكية,أقمت ليلتين,“رائعة ومريحه”. الفندق ممتاز حتى لو لم يكن 5 ن...,positive_feedback,low,positive,Gulf,False,Auto Response
1,21326,المجاز بريميير للشقق الفندقية,5,-,أقمت 7 ليالي,استثنائي. راحه وهدوء وممتاز ورائع وسوبر ديلوكس...,positive_feedback,low,positive,Gulf,False,Auto Response
2,65932,فندق بودل البريدة,4,-,أقمت ليلة واحدة,جيد. . المصعد بعيد عن الجناح,positive_feedback,low,positive,MSA,False,Auto Response
3,65731,بودل القصر,5,-,أقمت ليلة واحدة,استثنائي. فرصه رائعه لمن ارد الحياه الراقيه عل...,positive_feedback,low,positive,MSA,False,Auto Response
4,42042,فندق أنجم مكة,4,غرفة ديلوكس توأمية مطلة على الحرم,أقمت ليلة واحدة,جيد جداً. بوفيه الإفطار جدا رائع و لذيذ العمال...,positive_feedback,low,positive,Gulf,False,Auto Response
...,...,...,...,...,...,...,...,...,...,...,...,...
70,62700,فنادق ومنتجعات بيتش ريزورت بن ماجد,2,-,أقمت ليلة واحدة,“شعرت بالاكتئاب”. لم يعجبني شي. شعرت عندما اخب...,product_quality,high,negative,Gulf,True,CX Manager
71,6958,فندق ميلينيوم العقيق المدينة,2,غرفة قياسية كينغ,أقمت 12 ليلة,“زيادة الموظفين فى المناسبات مثل رمضان .”. الم...,product_quality,high,negative,Egyptian,True,CX Manager
72,27466,قصر المحمدية للاجنحة الفندقية,5,شقة من غرفة نوم واحدة,أقمت ليلة واحدة,“خدمة ممتازة جداً”. الخدمة والموقع والنظافة وح...,positive_feedback,low,positive,Gulf,False,Auto Response
73,50672,اسوار للاجنحة الفندقية,2,-,أقمت ليلتين,“الشقة رائعة”. الشقة مميزة. لايوجد خدمات مميزة...,positive_feedback,high,negative,Gulf,False,Auto Response
74,65772,بودل الورود,4,-,أقمت 5 ليالي,“كانت إقامة رائعة وجميلة .. شكراً طاقم العمل ب...,positive_feedback,low,positive,Gulf,False,Auto Response

In [29]:
sample = 1
print(test_dataset_filled["review"][sample])
print(test_dataset_filled[["intent","urgency","requires_human","routed_team"]].iloc[sample])

استثنائي. راحه وهدوء وممتاز ورائع وسوبر ديلوكس والعموم متعاون اقامتي اكثر من شهر ما اشتكيت من اي شيء. لايوجد فرن للطبخ الانترنت نوعاً ما مقبول
intent            positive_feedback
urgency                         low
requires_human                False
routed_team           Auto Response
Name: 1, dtype: object

In [30]:
sample = 10
print(test_dataset_filled["review"][sample])
print(test_dataset_filled[["intent","urgency","requires_human","routed_team"]].iloc[sample])

ضعيف. . النظافة سيئة جداً والسرير ليس مريحالتكيف لايعمل عالدافي لتدفئة الغرفة في فصل الشتاء
intent            product_quality
urgency                      high
requires_human               True
routed_team            CX Manager
Name: 10, dtype: object

In [31]:
sample = 20
print(test_dataset_filled["review"][sample])
print(test_dataset_filled[["intent","urgency","requires_human","routed_team"]].iloc[sample])

ممتاز. نشكر الاخ عبده اليماني على حسن الاستقبال والاخلاق العالية.
intent            positive_feedback
urgency                         low
requires_human                False
routed_team           Auto Response
Name: 20, dtype: object

In [32]:
sample = 30
print(test_dataset_filled["review"][sample])
print(test_dataset_filled[["intent","urgency","requires_human","routed_team"]].iloc[sample])

“مكان جميل للراحه”. كل شى اعجبنى. اغلاق البوابه الماديه من المول الى الفندق فى الساعه 12 من الليل وفتح البوابه الساعه 10 الرجاء اعاده النظر فى الموضوع
intent            positive_feedback
urgency                         low
requires_human                False
routed_team           Auto Response
Name: 30, dtype: object

In [33]:
sample = 40
print(test_dataset_filled["review"][sample])
print(test_dataset_filled[["intent","urgency","requires_human","routed_team"]].iloc[sample])

“الفندق مريح”. الموقع مناسبفي وسط الخدماتممتاز للمعتمرين. عدم توفر الواي فاي المجانيةرسومها مبالغ فيها بالنسبة لجودة الخدمةالفرش  قديم
intent            product_quality
urgency                      high
requires_human               True
routed_team            CX Manager
Name: 40, dtype: object

In [34]:
sample = 50
print(test_dataset_filled["review"][sample])
print(test_dataset_filled[["intent","urgency","requires_human","routed_team"]].iloc[sample])

ضعيف. لاشيء. لاشيء جميل لاشيء جديدخدمات سيئة
intent            product_quality
urgency                      high
requires_human               True
routed_team            CX Manager
Name: 50, dtype: object

In [35]:
test_dataset = pd.read_csv("test_dataset_with_adversarial.csv", encoding="utf-8-sig")

In [36]:
test_dataset

,order_id,product,rating,amount,date,review,intent,urgency,sentiment,dialect,requires_human,routed_team
0,58231,فندق أيلا بوادي,5,غرفة كوين كلاسيكية,أقمت ليلتين,“رائعة ومريحه”. الفندق ممتاز حتى لو لم يكن 5 ن...,positive_feedback,low,positive,Gulf,False,Auto Response
1,21326,المجاز بريميير للشقق الفندقية,5,-,أقمت 7 ليالي,استثنائي. راحه وهدوء وممتاز ورائع وسوبر ديلوكس...,positive_feedback,low,positive,Gulf,False,Auto Response
2,65932,فندق بودل البريدة,4,-,أقمت ليلة واحدة,جيد. . المصعد بعيد عن الجناح,positive_feedback,low,positive,MSA,False,Auto Response
3,65731,بودل القصر,5,-,أقمت ليلة واحدة,استثنائي. فرصه رائعه لمن ارد الحياه الراقيه عل...,positive_feedback,low,positive,MSA,False,Auto Response
4,42042,فندق أنجم مكة,4,غرفة ديلوكس توأمية مطلة على الحرم,أقمت ليلة واحدة,جيد جداً. بوفيه الإفطار جدا رائع و لذيذ العمال...,positive_feedback,low,positive,Gulf,False,Auto Response
...,...,...,...,...,...,...,...,...,...,...,...,...
93,90019,فندق الفيروز,1,غرفة ديلوكس,أقمت 3 ليالي,الفندق ممتاز جداً ومكانه رائع ونظيف وأنصح الجم...,product_quality,high,negative,Gulf,True,CX Manager
94,90020,فندق الريف,2,غرفة مزدوجة,أقمت ليلتين,اتصلت بالاستقبال ٧ مرات من الساعة ١١ الليل ولا...,delivery_issue,high,negative,Gulf,True,Logistics
95,90021,فندق الأفق,1,-,أقمت ليلة واحدة,سيء سيء سيء سيء سيء سيء سيء سيء سيء سيء سيء سي...,abusive_or_spam,high,negative,MSA,True,CX Manager
96,90022,فندق النهضة,5,غرفة قياسية,أقمت ليلة واحدة,الفندق جيد'; DROP TABLE reviews; -- الخدمة ممت...,abusive_or_spam,high,positive,MSA,True,CX Manager
97,90023,فندق الماس,1,غرفة بانورامية,أقمت ليلتين,تجربة استثنائية من نوع آخر تماماً! إيقاظي السا...,product_quality,high,negative,MSA,True,CX Manager

In [37]:
import re

def preprocess_review(text):
    if not isinstance(text, str):
        return ""

    # Remove URLs
    text = re.sub(r'http\S+|www\S+', ' ', text)

    # Remove Emails
    text = re.sub(r'\S+@\S+', ' ', text)

    # Remove Arabic Diacritics
    arabic_diacritics = re.compile("""
        ّ|َ|ً|ُ|ٌ|ِ|ٍ|ْ|ـ
    """, re.VERBOSE)
    text = re.sub(arabic_diacritics, '', text)

    # Normalize Arabic letters
    text = re.sub(r'[إأآا]', 'ا', text)
    text = re.sub(r'ى', 'ي', text)
    text = re.sub(r'ة', 'ه', text)

    # Remove English characters
    text = re.sub(r'[A-Za-z]', ' ', text)

    # Keep Arabic letters, digits, spaces
    text = re.sub(r'[^\u0600-\u06FF0-9\s]', ' ', text)

    # Remove repeated characters (جمييييل -> جميل)
    text = re.sub(r'(.)\1{2,}', r'\1', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [38]:
def compare(dataset, coulmn, index):
  print(f"Before: {dataset[coulmn][index]}")
  print(f"After: {preprocess_review(dataset[coulmn][index])}")

In [39]:
compare(test_dataset, 'review', 0)

Before: “رائعة ومريحه”. الفندق ممتاز حتى لو لم يكن 5 نجوم الموظفين وخاصه المدير متعاون جداا وحتى النادلات في المطعم بشوشات المسبح رائع للأطفال ...قريب من المول جداا جدااا بشكل عام احببت الاقامه فيه وسوف أعيد الزياره مرات ومرات. فقط ماء المسبح كان بااااادر جدا .. وأتمنى تدفأته قليل ليناسب الأطفال الصغار
After: رائعه ومريحه الفندق ممتاز حتي لو لم يكن 5 نجوم الموظفين وخاصه المدير متعاون جداا وحتي النادلات في المطعم بشوشات المسبح رائع للاطفال قريب من المول جداا جدا بشكل عام احببت الاقامه فيه وسوف اعيد الزياره مرات ومرات فقط ماء المسبح كان بادر جدا واتمني تدفاته قليل ليناسب الاطفال الصغار

In [40]:
compare(test_dataset, 'review', 52)

Before: “فندق ممتاز بعد النظر الي الانتقالات”. الفندق نظيف ومريح والمقابلة ممتازة جزاكم الله خيرا. الانتقال سئ معامله وامكانيات باص واحد لا يكفي مع بعد المسافه
After: فندق ممتاز بعد النظر الي الانتقالات الفندق نظيف ومريح والمقابله ممتازه جزاكم الله خيرا الانتقال سئ معامله وامكانيات باص واحد لا يكفي مع بعد المسافه

In [41]:
compare(test_dataset, 'review', 45)

Before: رائع. كل شي جميل. ارتفاع الاسعار بشكل مبالغ فيه
After: رائع كل شي جميل ارتفاع الاسعار بشكل مبالغ فيه

In [42]:
compare(test_dataset, 'review', 90)

Before: الفندق هذا فيه مشاكل بزاف! علاش الغرفة ما نظفاتش من بعد ما طلبناها؟ برشا أشياء ماشيات على خير: الماء السخون، الكهرباء ف الحمام، والإنترنت — كامل خاوي. مكانش خدمة يستاهل فيها هذا الثمن
After: الفندق هذا فيه مشاكل بزاف علاش الغرفه ما نظفاتش من بعد ما طلبناها؟ برشا اشياء ماشيات علي خير الماء السخون، الكهرباء ف الحمام، والانترنت كامل خاوي مكانش خدمه يستاهل فيها هذا الثمن

In [49]:
def csv_to_json(df):
    records = []
    for _, row in df.iterrows():
        records.append({
            "review": row["review"],
            "intent": row["intent"],
            "urgency": row["urgency"],"sentiment": row["sentiment"],
            "dialect": row["dialect"],
            "routed_team": row["routed_team"],"requires_human": row["requires_human"],
            "entities": {
                "order_id": row["order_id"],"product": row["product"],
                "amount": row["amount"],"date": row["date"]
            }
        })

    return records

In [53]:
Json_test_dataset = csv_to_json(test_dataset)

In [52]:
Json_test_dataset[0:2]

[{'review': '“رائعة ومريحه”. الفندق ممتاز حتى لو لم يكن 5 نجوم الموظفين وخاصه المدير متعاون جداا وحتى النادلات في المطعم بشوشات المسبح رائع للأطفال ...قريب من المول جداا جدااا بشكل عام احببت الاقامه فيه وسوف أعيد الزياره مرات ومرات. فقط ماء المسبح كان بااااادر جدا .. وأتمنى تدفأته قليل ليناسب الأطفال الصغار',
  'intent': 'positive_feedback',
  'urgency': 'low',
  'sentiment': 'positive',
  'dialect': 'Gulf',
  'routed_team': 'Auto Response',
  'requires_human': False,
  'entities': {'order_id': 58231,
   'product': 'فندق أيلا بوادي',
   'amount': 'غرفة كوين كلاسيكية',
   'date': 'أقمت ليلتين'}},
 {'review': 'استثنائي. راحه وهدوء وممتاز ورائع وسوبر ديلوكس والعموم متعاون اقامتي اكثر من شهر ما اشتكيت من اي شيء. لايوجد فرن للطبخ الانترنت نوعاً ما مقبول',
  'intent': 'positive_feedback',
  'urgency': 'low',
  'sentiment': 'positive',
  'dialect': 'Gulf',
  'routed_team': 'Auto Response',
  'requires_human': False,
  'entities': {'order_id': 21326,
   'product': 'المجاز بريميير للشقق الفندقية',
   'amount': '-',
   'date': 'أقمت 7 ليالي'}}]

In [56]:
import json

with open("test\\test_dataset.json", "w", encoding="utf-8") as f:
    json.dump(
        Json_test_dataset,
        f,
        ensure_ascii=False,
        indent=4
    )